### ISSUE TITLE
Question on LayerNorm in moead.py

### ISSUE THREAD

**Issue by daan1838** [TheStarOfMSY/MoEAD#3]
I'm reviewing the self.norms layer usage in moead.py's wide_transformer and noticed that self.norms is initialized with num_decoder * 4 layers.

However, in the loop, indices like 2*i, 2*i+1, 2*i+2, and 2*i+3 are used, which seems to result in reuse between iterations (e.g., 2*i+2 at i=0 overlapping with 2*i at i=1).

Is this reuse intended for optimization, or is it unintentional? Thanks for your clarification!

**Comment by TheStarOfMSY** [comment]
Thank you for your question! This is a code mistake. The used indices should be 4i, 4i+1, 4i+2, 4i+3. I will upload the correct code and the model trained again. Sorry again for my carelessness. I will also change the experiment result in readme.md later.
